force-app/main/default/objects/VDT_Data_Calculation__c.object
<CustomObject>
    <label>Data Calculation</label>
    <nameField>
        <displayFormat>DC-{00000}</displayFormat>
        <label>Data Calculation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>End_Date__c</fullName>
        <formula>IF (End_Year__c!=0,DATE(IF(End_Month__c=0, End_Year__c+1, End_Year__c), 1,1) -1, NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <formula>DATE(Start_Year__c , IF(Start_Month__c = 0, 1, Start_Month__c) , 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Queue</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VDT_Calculation_Date__c</fullName>
        <label>Calculation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>VDT_Job_End_Date__c</fullName>
        <label>Job End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>VDT_Job_Start_Date__c</fullName>
        <label>Job Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>VDT_Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/VDT_Data_Calculation__c/fields/Batches_Number__c.field-meta.xml
<CustomField>
    <fullName>Batches_Number__c</fullName>
    <label>Batches Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/VDT_FieldValuesOccurrencesBatch.cls
public with sharing class VDT_FieldValuesOccurrencesBatch implements Database.Batchable<SObject>, Database.Stateful, Database.AllowsCallouts {

    private VDT_Data_Calculation__c dataCalculationRecord;
    private VDT_FieldValuesOccurrencesBuilder builder;

    public VDT_FieldValuesOccurrencesBatch(VDT_Data_Calculation__c dataCalculationRecord) {
        this.dataCalculationRecord = dataCalculationRecord;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        try {
            String sobjectName = this.dataCalculationRecord.VDT_Object_Name__c;
            if (this.dataCalculationRecord.VDT_Object_Name__c == 'PersonAccount' || this.dataCalculationRecord.VDT_Object_Name__c == 'BusinessAccount') {
                sobjectName = 'Account';
            }
            List<String> fieldNames = new List<String>();

            for (Schema.SObjectField field : VDT_ObjectService.getAllAccessibleFieldsForObjectAndTypes(sobjectName, new List<DisplayType>{DisplayType.Picklist})) {
                fieldNames.add(field.getDescribe().getName());
            }
    
            this.builder = new VDT_FieldValuesOccurrencesBuilder(sobjectName, fieldNames);
            String query = 'SELECT ' + String.join(fieldNames, ',');
            
            String countryField = VDT_CustomMetadataService.getCountryFieldForObject(sobjectName);
            String dateField = VDT_CustomMetadataService.getDateFieldForObject(sobjectName);            
            if (query.indexOf(countryField) < 0) {
                query += ',' + countryField;
            }
    
            query += ' FROM ' + sobjectName + ' WHERE ' + countryField + ' != NULL';

            if (this.dataCalculationRecord.VDT_Object_Name__c == 'PersonAccount') {
                query += ' AND IsPersonAccount = TRUE';
            }
            if (this.dataCalculationRecord.VDT_Object_Name__c == 'BusinessAccount') {
                query += ' AND IsPersonAccount = FALSE';
            }
            if (this.dataCalculationRecord.Start_Date__c != NULL && this.dataCalculationRecord.End_Date__c != NULL) {
                query += ' AND {0} >= :startDate AND {0} <= :endDate';
            }
            String queryFormatted = String.format(query, new List<String>{
                dateField
            });
            this.dataCalculationRecord.VDT_Job_Start_Date__c = Datetime.now();
            this.dataCalculationRecord.Batches_Number__c = 0;
            update this.dataCalculationRecord;

            return Database.getQueryLocator(queryFormatted);            
        } catch (Exception e) {
            VDT_Log.get().add(e.getMessage() + '\n' + e.getStackTraceString(), VDT_LogSeverity.ERROR);
            VDT_Log.get().publish();
            VDT_DataCalculationService.sendStatusUpdateEvent(this.dataCalculationRecord.Id, VDT_DataCalculationService.STATUS_ERROR);            
            throw e; 
        }
    }

    public void execute(Database.BatchableContext bc, List<SObject> records) {
        try {
            this.dataCalculationRecord.Batches_Number__c += 1;
            update this.dataCalculationRecord;
            this.builder.withRecords(records).calculate();
        } catch (Exception e) {
            VDT_Log.get().add(e.getMessage() + '\n' + e.getStackTraceString(), VDT_LogSeverity.ERROR);
            VDT_Log.get().publish();
            VDT_DataCalculationService.sendStatusUpdateEvent(this.dataCalculationRecord.Id, VDT_DataCalculationService.STATUS_ERROR);            
            throw e;            
        }
    }

    public void finish(Database.BatchableContext bc) {
        try {
            this.dataCalculationRecord.VDT_Job_End_Date__c = Datetime.now();
            this.dataCalculationRecord.Status__c = VDT_DataCalculationService.STATUS_COMPLETED;
            this.dataCalculationRecord.VDT_Calculation_Date__c = Date.today();

            update this.dataCalculationRecord;

            VDT_AttachmentService.createAttachmentForRecord(
                this.builder.build(),
                VDT_ObjectService.FIELD_VALUES_OCCURRENCES_FILE_NAME,
                VDT_AttachmentService.JSON_FORMAT,
                this.dataCalculationRecord.Id
            );            
            VDT_EmailService.sendFieldValuesOccurrencesFinishedEmailNotification(this.dataCalculationRecord.VDT_Object_Name__c);
        } catch (Exception e) {
            VDT_Log.get().add(e.getMessage() + '\n' + e.getStackTraceString(), VDT_LogSeverity.ERROR);
            VDT_Log.get().publish();
            VDT_DataCalculationService.sendStatusUpdateEvent(this.dataCalculationRecord.Id, VDT_DataCalculationService.STATUS_ERROR);            
            throw e;            
        }
    }

}