force-app/main/default/objects/VDT_Log__e.object
<CustomObject>
    <label>Log</label>
    <pluralLabel>Logs</pluralLabel>
    <fields>
        <fullName>Log_Message__c</fullName>
        <label>Log Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Quiddity__c</fullName>
        <label>Quiddity</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Id__c</fullName>
        <label>Request Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <length>10</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/VDT_Log_Event__c.object
<CustomObject>
    <label>Log Event</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Log Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VDT_Log_Event__c/fields/Log_Data__c.field-meta.xml
<CustomField>
    <fullName>Log_Data__c</fullName>
    <label>Log Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VDT_Log_Event__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VDT_LogTriggerHandler.cls
/**
 * Trigger Handler for Account object
 */
public with sharing class VDT_LogTriggerHandler extends VDT_TriggerHandler.DelegateBase {

    public VDT_LogTriggerHandler() {}

    public override void afterInsert(Map<Id, sObject> newMap) {
        validateRun();
        setAfterInsert((Map<Id, VDT_Log__e>) newMap);
    }

    private void setAfterInsert(Map<Id, VDT_Log__e> newMap) {
        system.debug('newMap :: ' + newMap);
        List<VDT_Log_Event__c> events = new List<VDT_Log_Event__c>();

        for (VDT_Log__e event : newMap.values()) {
            events.add(
                new VDT_Log_Event__c(
                    Log_Data__c = event.Log_Message__c,
                    Quiddity__c = event.Quiddity__c,
                    Request_Id__c = event.Request_Id__c,
                    Severity__c = event.Severity__c
                )
            );
        }

        List<Database.SaveResult> res = Database.insert(events, false);
        for (Database.SaveResult saveRes : res) {
            if (!saveRes.isSuccess()) {
                System.debug(
                    LoggingLevel.ERROR,
                    'Failed to save log message: ' + saveRes
                );
            }
        }
    }
}