force-app/main/default/objects/VDT_Data_Calculation__c.object
<CustomObject>
    <label>Data Calculation</label>
    <nameField>
        <displayFormat>DC-{00000}</displayFormat>
        <label>Data Calculation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>End_Month__c</fullName>
        <label>End Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Year__c</fullName>
        <label>End Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Month__c</fullName>
        <label>Start Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Year__c</fullName>
        <label>Start Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Queue</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VDT_Calculation_Date__c</fullName>
        <label>Calculation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>VDT_Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/VDT_Data_Calculation__c/fields/Permission_Set_Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set_Profile_Name__c</fullName>
    <label>Permission Set/Profile Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VDT_Data_Calculation__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VDT_Data_Calculation__c/fields/VDT_Country__c.field-meta.xml
<CustomField>
    <fullName>VDT_Country__c</fullName>
    <label>Country</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VDT_DataCalculationDataFactory.cls
@IsTest
public with sharing class VDT_DataCalculationDataFactory {
    
    private VDT_Data_Calculation__c dataCalculation;

    public VDT_DataCalculationDataFactory() {
        this.dataCalculation = new VDT_Data_Calculation__c();
    }

    public VDT_DataCalculationDataFactory profileOrPermissionSet(String objectName) {
        this.dataCalculation.Permission_Set_Profile_Name__c = objectName;
        return this;
    }

    public VDT_DataCalculationDataFactory object(String objectApi) {
        this.dataCalculation.VDT_Object_Name__c = objectApi;
        return this;
    }

    public VDT_DataCalculationDataFactory countries(List<String> countries) {
        this.dataCalculation.VDT_Country__c = String.join(countries, ',');
        return this;
    }

    public VDT_DataCalculationDataFactory startYearAndMonth(Integer year, Integer month) {
        if (year != null) {
            this.dataCalculation.Start_Year__c = year;
        }
        if (month != null) {
            this.dataCalculation.Start_Month__c = month;
        }
        return this;
    }

    public VDT_DataCalculationDataFactory endYearAndMonth(Integer year, Integer month) {
        if (year != null) {
            this.dataCalculation.End_Year__c = year;
        }
        if (month != null) {
            this.dataCalculation.End_Month__c = month;
        }
        return this;
    }

    public VDT_DataCalculationDataFactory calculationDate(Date calculationDate) {
        this.dataCalculation.VDT_Calculation_Date__c = calculationDate;
        return this;
    }

    public VDT_DataCalculationDataFactory country(String country) {
        this.dataCalculation.VDT_Country__c = country;
        return this;
    }

    public VDT_DataCalculationDataFactory status(String status) {
        this.dataCalculation.Status__c = status;
        return this;
    }

    public VDT_DataCalculationDataFactory territory(String territory) {
        this.dataCalculation.Territory__c = territory;
        return this;
    }

    public VDT_DataCalculationDataFactory recordType(String recordTypeName) {
        Id recordTypeId = Schema.SObjectType.VDT_Data_Calculation__c.getRecordTypeInfosByDeveloperName().get(recordTypeName).getRecordTypeId();
        this.dataCalculation.RecordTypeId = recordTypeId;
        return this;
    }

    public VDT_DataCalculationDataFactory insertRecord() {
        insert this.dataCalculation;
        return this;
    }

    public VDT_DataCalculationDataFactory addAttachment(String name, String content, String format) {
        VDT_AttachmentService.createAttachmentForRecord(content, name, format, this.dataCalculation.Id);
        return this;
    }

    public VDT_Data_Calculation__c getRecord() {
        return this.dataCalculation;
    }
}