force-app/main/default/objects/VDT_Log__e.object
<CustomObject>
    <label>Log</label>
    <pluralLabel>Logs</pluralLabel>
    <fields>
        <fullName>Log_Message__c</fullName>
        <label>Log Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Quiddity__c</fullName>
        <label>Quiddity</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Id__c</fullName>
        <label>Request Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <length>10</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/VDT_Log_Event__c.object
<CustomObject>
    <label>Log Event</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Log Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VDT_Log_Event__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VDT_LogTriggerTest.cls
@IsTest
public with sharing class VDT_LogTriggerTest {

    @IsTest
    static void shouldInsertLogRecord_WhenEventFired(){
        
        VDT_Log__e logEvent = new VDT_Log__e(
            Log_Message__c = 'Log From Apex Class',
            Quiddity__c = 'Test',
            Request_Id__c = '1',
            Severity__c = 'WARN'
        );

        Test.startTest();
        Database.SaveResult sr = Eventbus.publish(logEvent);
        Test.stopTest();
        System.assert(sr.isSuccess());

        List<VDT_Log_Event__c> newLogEvents = [SELECT Id, Severity__c FROM VDT_Log_Event__c];
        System.assert(!newLogEvents.isEmpty());
        System.assertEquals('WARN', newLogEvents.get(0).Severity__c);
    }
}