force-app/main/default/objects/VDT_Calculation_Status_Update__e/VDT_Calculation_Status_Update__e.object-meta.xml
<CustomObject>
    <label>Calculation Status Update</label>
    <pluralLabel>Calculation Status Updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/VDT_Calculation_Status_Update__e/fields/Calculation_Id__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Id__c</fullName>
    <label>Calculation Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VDT_Data_Calculation__c.object
<CustomObject>
    <label>Data Calculation</label>
    <nameField>
        <displayFormat>DC-{00000}</displayFormat>
        <label>Data Calculation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Queue</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/VDT_CalculationStatusUpdateTriggerTest.cls
@IsTest
public with sharing class VDT_CalculationStatusUpdateTriggerTest {

    @IsTest
    static void shouldSetStatusToError_WhenEventFired(){
        
        VDT_Data_Calculation__c calc = new VDT_DataCalculationDataFactory()
            .status('In Progress')
            .recordType(VDT_DataCalculationSelector.MASTER_ANALYSIS_RECORD_TYPE_DEV)
            .insertRecord()
            .getRecord();
        VDT_Calculation_Status_Update__e calculationUpdate = new VDT_Calculation_Status_Update__e(
            Calculation_Id__c = calc.Id,
            Status__c = 'Error'
        );

        Test.startTest();
        Database.SaveResult sr = Eventbus.publish(calculationUpdate);
        Test.stopTest();
        System.assert(sr.isSuccess());

        VDT_Data_Calculation__c calcUpdated = [SELECT Id, Status__c FROM VDT_Data_Calculation__c WHERE Id = :calc.Id];
        System.assertEquals('Error', calcUpdated.Status__c);
    }

    @IsTest
    static void shouldSetStatusToCompleted_WhenEventFired(){
        
        VDT_Data_Calculation__c calc = new VDT_DataCalculationDataFactory()
            .status('In Progress')
            .recordType(VDT_DataCalculationSelector.MASTER_ANALYSIS_RECORD_TYPE_DEV)
            .insertRecord()
            .getRecord();
        VDT_Calculation_Status_Update__e calculationUpdate = new VDT_Calculation_Status_Update__e(
            Calculation_Id__c = calc.Id,
            Status__c = 'Completed'
        );

        Test.startTest();
        Database.SaveResult sr = Eventbus.publish(calculationUpdate);
        Test.stopTest();
        System.assert(sr.isSuccess());

        VDT_Data_Calculation__c calcUpdated = [SELECT Id, Status__c FROM VDT_Data_Calculation__c WHERE Id = :calc.Id];
        System.assertEquals('Completed', calcUpdated.Status__c);
    }

}