force-app/main/default/objects/VDT_Calculation_Status_Update__e/VDT_Calculation_Status_Update__e.object-meta.xml
<CustomObject>
    <label>Calculation Status Update</label>
    <pluralLabel>Calculation Status Updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/VDT_Calculation_Status_Update__e/fields/Calculation_Id__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Id__c</fullName>
    <label>Calculation Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VDT_Data_Calculation__c.object
<CustomObject>
    <label>Data Calculation</label>
    <nameField>
        <displayFormat>DC-{00000}</displayFormat>
        <label>Data Calculation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Queue</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/VDT_CalculationStatusTriggerHandler.cls
public with sharing class VDT_CalculationStatusTriggerHandler extends VDT_TriggerHandler.DelegateBase {
    public VDT_CalculationStatusTriggerHandler() {}

    public override void afterInsert(Map<Id, sObject> newMap) {
        validateRun();
        setAfterInsert((Map<Id, VDT_Calculation_Status_Update__e>) newMap);
    }

    private void setAfterInsert(Map<Id, VDT_Calculation_Status_Update__e> newMap) {
        List<VDT_Data_Calculation__c> calculations = new List<VDT_Data_Calculation__c>();

        for (VDT_Calculation_Status_Update__e event : newMap.values()) {
            calculations.add(
                new VDT_Data_Calculation__c(
                    Id = event.Calculation_Id__c,
                    Status__c = event.Status__c
                )
            );
        }

        List<Database.SaveResult> res = Database.update(calculations, false);
        for (Database.SaveResult saveRes : res) {
            if (!saveRes.isSuccess()) {
                VDT_Log.get().add('Failed to update calculation status: ' + saveRes, VDT_LogSeverity.ERROR);
                VDT_Log.get().publish();
            }
        }
    }
}