force-app/main/default/objects/EM_Event_vod__c/fields/VDT_Product_Catalog__c.field-meta.xml
<CustomField>
    <fullName>VDT_Product_Catalog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Catalog</label>
    <referenceTo>Product_vod__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VDT_Account_Record_Type_Mapping__mdt/VDT_Account_Record_Type_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Object used to configure whether the Account Record type should be included on OneKey customers or not.</description>
    <label>VDT Account Record Type Mapping</label>
    <pluralLabel>VDT Account Record Type Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/VDT_Account_Record_Type_Mapping__mdt/fields/Account_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Account_Record_Types__c</fullName>
    <description>List of Record Types separated by comma</description>
    <inlineHelpText>List of Record Types separated by comma</inlineHelpText>
    <label>Account Record Types</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VDT_Custom_Objects_Field_Mapping__mdt/VDT_Custom_Objects_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>VDT Custom Objects Field Mapping</label>
    <pluralLabel>VDT Custom Objects Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/VDT_Custom_Objects_Field_Mapping__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VDT_General_Setting__mdt.object
<CustomObject>
    <label>VDT General Setting</label>
    <pluralLabel>VDT General Settings</pluralLabel>
    <fields>
        <fullName>Apex_Async_Execution_Daily_Allocation__c</fullName>
        <label>Apex Async Execution Daily Allocation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <label>Batch Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default_Country_Code_Field__c</fullName>
        <label>Default Country Code Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maximum_Calculation_Requests__c</fullName>
        <label>Maximum Calculation Requests</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Running_Calculations__c</fullName>
        <label>Maximum Running Calculations</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Standard_Field_Identifier__c</fullName>
        <label>Standard Field Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date_Year_Decrement__c</fullName>
        <label>Start Date Year Decrement</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/objects/VDT_General_Setting__mdt/fields/International_Country__c.field-meta.xml
<CustomField>
    <fullName>International_Country__c</fullName>
    <label>International Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VDT_General_Setting__mdt/fields/VDT_Default_Countries__c.field-meta.xml
<CustomField>
    <fullName>VDT_Default_Countries__c</fullName>
    <label>Default Countries</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VDT_General_Setting__mdt/fields/VDT_Default_Specialty_Field__c.field-meta.xml
<CustomField>
    <fullName>VDT_Default_Specialty_Field__c</fullName>
    <label>Default Specialty Field</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VDT_General_Setting__mdt/fields/VDT_Is_Territory_Management_Active__c.field-meta.xml
<CustomField>
    <fullName>VDT_Is_Territory_Management_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VDT Is Territory Management Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VDT_KPI_by_Country__mdt/VDT_KPI_by_Country__mdt.object-meta.xml
<CustomObject>
    <label>VDT KPI by Country</label>
    <pluralLabel>VDT KPI by Countries</pluralLabel>
</CustomObject>

force-app/main/default/objects/VDT_KPI_by_Country__mdt/fields/VDT_Country__c.field-meta.xml
<CustomField>
    <fullName>VDT_Country__c</fullName>
    <label>VDT Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VDT_KPI_by_Country__mdt/fields/VDT_KPI_Configuration__c.field-meta.xml
<CustomField>
    <fullName>VDT_KPI_Configuration__c</fullName>
    <label>VDT KPI Configuration</label>
    <referenceTo>VDT_KPI_Configuration__mdt</referenceTo>
    <relationshipLabel>VDT KPI by Countries</relationshipLabel>
    <relationshipName>VDT_KPI_by_Countries</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/VDT_KPI_by_Country__mdt/fields/VDT_Target__c.field-meta.xml
<CustomField>
    <fullName>VDT_Target__c</fullName>
    <label>VDT_Target</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VDT_KPI_Configuration__mdt/VDT_KPI_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>VDT KPI Configuration</label>
    <pluralLabel>VDT KPI Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/VDT_KPI_Configuration__mdt/fields/VDT_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>VDT_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VDT_KPI_Configuration__mdt/fields/VDT_Type__c.field-meta.xml
<CustomField>
    <fullName>VDT_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>higher</fullName>
                <default>true</default>
                <label>Higher is better</label>
            </value>
            <value>
                <fullName>lower</fullName>
                <label>Lower is better</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VDT_Object_Batch_Size_Mapping__mdt.object
<CustomObject>
    <label>VDT Object Batch Size Mapping</label>
    <pluralLabel>VDT Object Batch Size Mappings</pluralLabel>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <label>Batch Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/objects/VDT_Object_Country_Field_Mapping__mdt.object
<CustomObject>
    <description>configurations of field used to store country code for objects</description>
    <label>VDT Object Country Field Mapping</label>
    <pluralLabel>VDT Object Country Field Mappings</pluralLabel>
    <fields>
        <fullName>Country_Field_Reference__c</fullName>
        <label>Country Field Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/VDT_Object_Product_Field_Mapping__mdt/VDT_Object_Product_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Stores what field should be used to reference the Product Catalog on each Custom Object.
Label must have the Custom Object API Name to configure.
Product Field Reference: Lookup or Master Detail field on the object specified on the Label property</description>
    <label>VDT Object Product Field Mapping</label>
    <pluralLabel>VDT Object Product Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/VDT_Object_Product_Field_Mapping__mdt/fields/Product_Field_Reference__c.field-meta.xml
<CustomField>
    <fullName>Product_Field_Reference__c</fullName>
    <label>Product Field Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VDT_Tab__mdt/VDT_Tab__mdt.object-meta.xml
<CustomObject>
    <description>Used to control which menu items will be displayed on the app&apos;s left side menu</description>
    <label>VDT Tab</label>
    <pluralLabel>VDT Tabs</pluralLabel>
</CustomObject>

force-app/main/default/classes/VDT_CustomMetadataServiceTest.cls
@IsTest
public inherited sharing class VDT_CustomMetadataServiceTest {

    @IsTest
    static void methodName() {
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_Tab__mdt', 
        (List<VDT_Tab__mdt>) JSON.deserialize('[{"DeveloperName": "home"}, {"DeveloperName": "master_data_analysis"}]', List<VDT_Tab__mdt>.class));
        List<String> menuOptions = new List<String>();
        Test.startTest();
        String csvOptions = VDT_CustomMetadataService.getActiveMenuOptions();
        menuOptions = csvOptions.split(',');
        Test.stopTest();
        System.assert(!menuOptions.isEmpty());
        System.assertEquals(2, menuOptions.size());
    }

    @IsTest
    static void shouldReturnFieldNameForObject() {
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_Custom_Objects_Field_Mapping__mdt', 
            (List<VDT_Custom_Objects_Field_Mapping__mdt>) JSON.deserialize('[{"Field_API_Name__c": "VDT_Status__c"}]', List<VDT_Custom_Objects_Field_Mapping__mdt>.class));
        Test.startTest();
        String fieldAPI = VDT_CustomMetadataService.getFieldNameForCustomObject('Veeva', 'PRODUCT_VOD_STATUS');
        Test.stopTest();
        system.assertEquals('VDT_Status__c', fieldAPI);
    }

    @IsTest
    static void shouldReturnFieldApiNameForEvents() {
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_Object_Product_Field_Mapping__mdt', 
            (List<VDT_Object_Product_Field_Mapping__mdt>) JSON.deserialize('[{"Product_Field_Reference__c": "VDT_Product_Catalog__c"}]', List<VDT_Object_Product_Field_Mapping__mdt>.class));
        Test.startTest();
        String productField = VDT_CustomMetadataService.getProductFieldForObject('EM_Event_vod__c');
        Test.stopTest();
        system.assertEquals('VDT_Product_Catalog__c', productField);
        
    }

    @IsTest
    static void shouldReturnListOfDefaultCountries() {
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_General_Setting__mdt', 
            (List<VDT_General_Setting__mdt>) JSON.deserialize('[{"VDT_Default_Countries__c": "BE,FR,DE,UK"}]', List<VDT_General_Setting__mdt>.class));
        Test.startTest();
        List<VDT_OptionWrapper> countryOptions = VDT_CustomMetadataService.getDefaultCountries();
        Test.stopTest();
        System.assertEquals(4, countryOptions.size());
    }

    @IsTest
    static void shouldReturnInternationalCountryValue() {
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_General_Setting__mdt', 
            (List<VDT_General_Setting__mdt>) JSON.deserialize('[{"International_Country__c": "INT"}]', List<VDT_General_Setting__mdt>.class));        
        Test.startTest();
        String internationalCountry = VDT_CustomMetadataService.getInternationalCountryValue();
        Test.stopTest();
        System.assertEquals('INT', internationalCountry);
    }

    @IsTest
    static void shouldReturnTerritoryActiveTrue() {
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_General_Setting__mdt', 
            (List<VDT_General_Setting__mdt>) JSON.deserialize('[{"VDT_Is_Territory_Management_Active__c": true}]', List<VDT_General_Setting__mdt>.class));
        Test.startTest();
        Boolean isTerritoryActive = VDT_CustomMetadataService.isTerritoryManagementActive();
        Test.stopTest();
        System.assert(isTerritoryActive);
    }

    @IsTest
    static void shouldReturnActiveKPIConfigurations() {
        String jsonObjects = String.format('[{0}, {1}, {2}]', new List<String> {
            '{"MasterLabel": "Onekey vs Non One Key", "VDT_Type__c": "higher", "VDT_Is_Active__c": true}',
            '{"MasterLabel": "Onekey aligned to territories", "VDT_Type__c": "higher", "VDT_Is_Active__c": true}',
            '{"MasterLabel": "Onekey Without visit", "VDT_Type__c": "lower", "VDT_Is_Active__c": true}'
        });
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_KPI_Configuration__mdt', 
            (List<VDT_KPI_Configuration__mdt>) JSON.deserialize(jsonObjects, List<VDT_KPI_Configuration__mdt>.class));
        
        Test.startTest();
        List<VDT_KPI_Configuration__mdt> kpis = VDT_CustomMetadataService.getActiveKpiConfigurations();
        Test.stopTest();
        System.assertEquals(3, kpis.size());
    }

    @IsTest
    static void shouldReturnKpiConfigurationsByCountry() {
        String jsonObjects = String.format('[{0}]', new List<String> {
            '{"VDT_Country__c": "DE", "VDT_KPI_Configuration__r.DeveloperName": "Onekey_vs_Non_One_Key", "VDT_Target__c": 95}'
        });
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_KPI_by_Country__mdt', 
            (List<VDT_KPI_by_Country__mdt>) JSON.deserialize(jsonObjects, List<VDT_KPI_by_Country__mdt>.class));
        Test.startTest();
        Map<String, Decimal> kpiByCountry = VDT_CustomMetadataService.getCountryKpiConfigurations();
        Test.stopTest();
        System.assertEquals(1, kpiByCountry.size());
    }

    @IsTest
    static void shouldReturnAccountRecordTypesByType() {
        String jsonObjects = String.format('[{0}, {1}]', new List<String> {
            '{"DeveloperName": "External_Customers", "Account_Record_Types__c": "MCO_vod,Hospital_vod,Laboratory_vod"}',
            '{"DeveloperName": "Internal_Customers", "Account_Record_Types__c": "Institution_vod,Professional_vod"}'
        });
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_Account_Record_Type_Mapping__mdt', 
            (List<VDT_Account_Record_Type_Mapping__mdt>) JSON.deserialize(jsonObjects, List<VDT_Account_Record_Type_Mapping__mdt>.class));        
        Test.startTest();
        Map<String, List<String>> accountRecordTypes = VDT_CustomMetadataService.getAccountRecordTypesByType();
        Test.stopTest();
        System.assertEquals(3, accountRecordTypes.get('External_Customers').size());
        System.assertEquals(2, accountRecordTypes.get('Internal_Customers').size());
    }

    @IsTest
    static void shouldReturnAccountSpecialtyField() {
        String jsonObjects = String.format('[{0}]', new List<String> {
            '{"VDT_Default_Specialty_Field__c": "VDT_Specialty_vod__c"}'
        });
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_General_Setting__mdt', 
            (List<VDT_General_Setting__mdt>) JSON.deserialize(jsonObjects, List<VDT_General_Setting__mdt>.class));
        Test.startTest();
        String specialtyField = VDT_CustomMetadataService.getAccountSpecialtyField();
        Test.stopTest();
        System.assertEquals('VDT_Specialty_vod__c', specialtyField);
    }

    @IsTest
    static void shouldReturnBatchSizeForObject() {
        String jsonObjects = String.format('[{0}]', new List<String> {
            '{"Batch_Size__c": 200}'
        });
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_Object_Batch_Size_Mapping__mdt', 
            (List<VDT_Object_Batch_Size_Mapping__mdt>) JSON.deserialize(jsonObjects, List<VDT_Object_Batch_Size_Mapping__mdt>.class));        
        Test.startTest();
        Integer batchSize = VDT_CustomMetadataService.getBatchSizeForObject('Account');
        Test.stopTest();
        System.assertEquals(200, batchSize);
    }

    @IsTest
    static void shouldReturnDefaultBatchSize() {
        String jsonObjects = String.format('[{0}]', new List<String> {
            '{"Batch_Size__c": 200}'
        });
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_General_Setting__mdt', 
            (List<VDT_General_Setting__mdt>) JSON.deserialize(jsonObjects, List<VDT_General_Setting__mdt>.class));        
        Test.startTest();
        Integer defaultBatchSize = VDT_CustomMetadataService.getDefaultBatchSize();
        Test.stopTest();
        System.assertEquals(200, defaultBatchSize);
    }

    @IsTest
    static void shouldReturnDailyAllocationValue() {
        String jsonObjects = String.format('[{0}]', new List<String> {
            '{"Apex_Async_Execution_Daily_Allocation__c": 50.00}'
        });
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_General_Setting__mdt', 
            (List<VDT_General_Setting__mdt>) JSON.deserialize(jsonObjects, List<VDT_General_Setting__mdt>.class));
        Test.startTest();
        Decimal dailyAllocation = VDT_CustomMetadataService.getDailyAsyncExecutionAllocation();
        Test.stopTest();
        System.assertEquals(50.00, dailyAllocation);
    }

    @IsTest
    static void shouldReturnCountryFieldForObject() {
        Test.startTest();
        String countryField = VDT_CustomMetadataService.getCountryFieldForObject(null);
        Test.stopTest();

        List<VDT_General_Setting__mdt> generalSettings = [
            SELECT  Default_Country_Code_Field__c
            FROM    VDT_General_Setting__mdt
            WHERE   DeveloperName = :VDT_CustomMetadataService.DEFAULT_APP_SETTINGS
        ];

        system.assertEquals(generalSettings[0].Default_Country_Code_Field__c, countryField);
    }

    @IsTest
    static void shouldReturnCountryFieldForObjectWithPreset() {
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_Object_Country_Field_Mapping__mdt', 
            (List<VDT_Object_Country_Field_Mapping__mdt>) JSON.deserialize('[{"Country_Field_Reference__c": "Country_Field__c"}]', List<VDT_Object_Country_Field_Mapping__mdt>.class));
        
        Test.startTest();
        String countryField = VDT_CustomMetadataService.getCountryFieldForObject(null);
        Test.stopTest();
        
        system.assertEquals('Country_Field__c', countryField);
    }

    @IsTest
    static void shouldReturnDefaultCountryFieldForObject() {
        Test.startTest();
        String defaultLanguageField = VDT_CustomMetadataService.getDefaultCountryField();
        Test.stopTest();
        List<VDT_General_Setting__mdt> generalSettings = [
            SELECT  Default_Country_Code_Field__c
            FROM    VDT_General_Setting__mdt
            WHERE   DeveloperName = :VDT_CustomMetadataService.DEFAULT_APP_SETTINGS
        ];

        system.assertEquals(generalSettings[0].Default_Country_Code_Field__c, defaultLanguageField);
    }

    @IsTest
    static void shouldReturnDefaultCountryFieldForObjectWithPreset() {
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_General_Setting__mdt', 
            (List<VDT_General_Setting__mdt>) JSON.deserialize('[{"Default_Country_Code_Field__c": "XX"}]', List<VDT_General_Setting__mdt>.class));
        
        Test.startTest();
        String defaultLanguageField = VDT_CustomMetadataService.getDefaultCountryField();
        Test.stopTest();

        system.assertEquals('XX', defaultLanguageField);
    }

    @IsTest
    static void shouldReturnStartDateYearDecrement() {
        Integer yearDecrement = VDT_CustomMetadataService.getStartDateYearDecrement();
        List<VDT_General_Setting__mdt> generalSettings = [
            SELECT  Start_Date_Year_Decrement__c
            FROM    VDT_General_Setting__mdt
            WHERE   DeveloperName = :VDT_CustomMetadataService.DEFAULT_APP_SETTINGS
        ];

        system.assertEquals(generalSettings[0].Start_Date_Year_Decrement__c, yearDecrement);
    }

    @IsTest
    static void shouldReturnStartDateYearDecrementWithPreset() {
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_General_Setting__mdt', 
            (List<VDT_General_Setting__mdt>) JSON.deserialize('[{"Start_Date_Year_Decrement__c": "3"}]', List<VDT_General_Setting__mdt>.class));
        
        Test.startTest();
        Integer yearDecrement = VDT_CustomMetadataService.getStartDateYearDecrement();
        Test.stopTest();

        system.assertEquals(3, yearDecrement);
    }

    @IsTest
    static void shouldReturnMaxNumberOfCalculationRequests() {
        Integer maxRequestsNum = VDT_CustomMetadataService.getMaxNumberOfCalculationRequests();
        List<VDT_General_Setting__mdt> generalSettings = [
            SELECT  Maximum_Calculation_Requests__c
            FROM    VDT_General_Setting__mdt
            WHERE   DeveloperName = :VDT_CustomMetadataService.DEFAULT_APP_SETTINGS
        ];
        
        system.assertEquals(generalSettings[0].Maximum_Calculation_Requests__c, maxRequestsNum);
    }

    @IsTest
    static void shouldReturnMaxNumberOfCalculationRequestsWithPreset() {
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_General_Setting__mdt', 
            (List<VDT_General_Setting__mdt>) JSON.deserialize('[{"Maximum_Calculation_Requests__c": "10"}]', List<VDT_General_Setting__mdt>.class));
        
        Test.startTest();
        Integer maxRequestsNum = VDT_CustomMetadataService.getMaxNumberOfCalculationRequests();
        Test.stopTest();

        system.assertEquals(10, maxRequestsNum);
    }

    @IsTest
    static void shouldReturnMaxNumberOfRunningCalculations() {
        Integer maxRunningCalc = VDT_CustomMetadataService.getMaxNumberOfRunningCalculations();
        List<VDT_General_Setting__mdt> generalSettings = [
            SELECT  Maximum_Running_Calculations__c
            FROM    VDT_General_Setting__mdt
            WHERE   DeveloperName = :VDT_CustomMetadataService.DEFAULT_APP_SETTINGS
        ];
        
        system.assertEquals(generalSettings[0].Maximum_Running_Calculations__c, maxRunningCalc);
    }

    @IsTest
    static void shouldReturnMaxNumberOfRunningCalculationsWithPreset() {
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_General_Setting__mdt', 
            (List<VDT_General_Setting__mdt>) JSON.deserialize('[{"Maximum_Running_Calculations__c": "2"}]', List<VDT_General_Setting__mdt>.class));
        
        Test.startTest();
        Integer maxRunningCalc = VDT_CustomMetadataService.getMaxNumberOfRunningCalculations();
        Test.stopTest();

        system.assertEquals(2, maxRunningCalc);
    }

    @IsTest
    static void shouldReturnStandardFieldIdentifier() {
        String identifier = VDT_CustomMetadataService.getStandardFieldIdentifier();
        List<VDT_General_Setting__mdt> generalSettings = [
            SELECT  Standard_Field_Identifier__c
            FROM    VDT_General_Setting__mdt
            WHERE   DeveloperName = :VDT_CustomMetadataService.DEFAULT_APP_SETTINGS
        ];
        
        system.assertEquals(generalSettings[0].Standard_Field_Identifier__c, identifier);
    }

    @IsTest
    static void shouldReturnStandardFieldIdentifierWithPreset() {
        VDT_CustomMetadataService.customMetadataWithRecords.put('VDT_General_Setting__mdt', 
            (List<VDT_General_Setting__mdt>) JSON.deserialize('[{"Standard_Field_Identifier__c": "test"}]', List<VDT_General_Setting__mdt>.class));
        
        Test.startTest();
        String identifier = VDT_CustomMetadataService.getStandardFieldIdentifier();
        Test.stopTest();

        system.assertEquals('test', identifier);
    }
}